import Uniform from "../models/Uniform"

export const createUniforms = async () => {
    const UniformData = [
        { 
          id: 1,
          name: 'Jas Almamater',
          price: 160000,
          stock: 1000,
          image: 'jas_almamater.png',
          size: 'S',
          product_type_id: 1,
        },
        { 
          id: 2,
          name: 'Jas Almamater',
          price: 160000,
          stock: 1000,
          image: 'jas_almamater.png',
          size: 'M',
          product_type_id: 1,
        },
        { 
          id: 3,
          name: 'Jas Almamater',
          price: 160000,
          stock: 1000,
          image: 'jas_almamater.png',
          size: 'L',
          product_type_id: 1,
        },
        { 
          id: 4,
          name: 'Jas Almamater',
          price: 160000,
          stock: 1000,
          image: 'jas_almamater.png',
          size: 'XL',
          product_type_id: 1,
        },
        { 
          id: 5,
          name: 'Seragam Olahraga',
          price: 165000,
          stock: 1000,
          image: 'seragam_olahraga.png',
          size: 'S',
          product_type_id: 1,
        },
        { 
          id: 6,
          name: 'Seragam Olahraga',
          price: 165000,
          stock: 1000,
          image: 'seragam_olahraga.png',
          size: 'M',
          product_type_id: 1,
        },
        { 
          id: 7,
          name: 'Seragam Olahraga',
          price: 165000,
          stock: 1000,
          image: 'seragam_olahraga.png',
          size: 'L',
          product_type_id: 1,
        },
        { 
          id: 8,
          name: 'Seragam Olahraga',
          price: 165000,
          stock: 1000,
          image: 'seragam_olahraga.png',
          size: 'XL',
          product_type_id: 1,
        },
        { 
          id: 9,
          name: 'Baju Batik',
          price: 115000,
          stock: 1000,
          image: 'baju_batik.png',
          size: 'S',
          product_type_id: 1,
        },
        { 
          id: 10,
          name: 'Baju Batik',
          price: 115000,
          stock: 1000,
          image: 'baju_batik.png',
          size: 'M',
          product_type_id: 1,
        },
        { 
          id: 11,
          name: 'Baju Batik',
          price: 115000,
          stock: 1000,
          image: 'baju_batik.png',
          size: 'L',
          product_type_id: 1,
        },
        { 
          id: 12,
          name: 'Baju Batik',
          price: 115000,
          stock: 1000,
          image: 'baju_batik.png',
          size: 'XL',
          product_type_id: 1,
        },
        { 
          id: 13,
          name: 'Kebaya',
          price: 115000,
          stock: 1000,
          image: 'kebaya.png',
          size: 'S',
          product_type_id: 1,
        },
        { 
          id: 14,
          name: 'Kebaya',
          price: 115000,
          stock: 1000,
          image: 'kebaya.png',
          size: 'M',
          product_type_id: 1,
        },
        { 
          id: 15,
          name: 'Kebaya',
          price: 115000,
          stock: 1000,
          image: 'kebaya.png',
          size: 'L',
          product_type_id: 1,
        },
        { 
          id: 16,
          name: 'Kebaya',
          price: 115000,
          stock: 1000,
          image: 'kebaya.png',
          size: 'XL',
          product_type_id: 1,
        },
        { 
          id: 17,
          name: 'Pangsi',
          price: 165000,
          stock: 1000,
          image: 'pangsi.png',
          size: 'S',
          product_type_id: 1,
        },
        { 
          id: 18,
          name: 'Pangsi',
          price: 165000,
          stock: 1000,
          image: 'pangsi.png',
          size: 'M',
          product_type_id: 1,
        },
        { 
          id: 19,
          name: 'Pangsi',
          price: 165000,
          stock: 1000,
          image: 'pangsi.png',
          size: 'L',
          product_type_id: 1,
        },
        { 
          id: 20,
          name: 'Pangsi',
          price: 165000,
          stock: 1000,
          image: 'pangsi.png',
          size: 'XL',
          product_type_id: 1,
        },
        { 
          id: 21,
          name: 'Jas Laboratorium',
          price: 110000,
          stock: 1000,
          image: 'jas_lab.png',
          size: 'S',
          product_type_id: 1,
        },
        { 
          id: 22,
          name: 'Jas Laboratorium',
          price: 110000,
          stock: 1000,
          image: 'jas_lab.png',
          size: 'M',
          product_type_id: 1,
        },
        { 
          id: 23,
          name: 'Jas Laboratorium',
          price: 110000,
          stock: 1000,
          image: 'jas_lab.png',
          size: 'L',
          product_type_id: 1,
        },
        { 
          id: 24,
          name: 'Jas Laboratorium',
          price: 110000,
          stock: 1000,
          image: 'jas_lab.png',
          size: 'XL',
          product_type_id: 1,
        },
        { 
          id: 25,
          name: 'Kemeja RPL',
          price: 160000,
          stock: 1000,
          image: 'kemeja_rpl.png',
          size: 'S',
          product_type_id: 1,
        },
        { 
          id: 26,
          name: 'Kemeja RPL',
          price: 160000,
          stock: 1000,
          image: 'kemeja_rpl.png',
          size: 'M',
          product_type_id: 1,
        },
        { 
          id: 27,
          name: 'Kemeja RPL',
          price: 160000,
          stock: 1000,
          image: 'kemeja_rpl.png',
          size: 'L',
          product_type_id: 1,
        },
        { 
          id: 28,
          name: 'Kemeja RPL',
          price: 160000,
          stock: 1000,
          image: 'kemeja_rpl.png',
          size: 'XL',
          product_type_id: 1,
        },
        { 
          id: 29,
          name: 'Kemeja TKJ',
          price: 160000,
          stock: 1000,
          image: 'kemeja_tkj.png',
          size: 'S',
          product_type_id: 1,
        },
        { 
          id: 30,
          name: 'Kemeja TKJ',
          price: 160000,
          stock: 1000,
          image: 'kemeja_tkj.png',
          size: 'M',
          product_type_id: 1,
        },
        { 
          id: 31,
          name: 'Kemeja TKJ',
          price: 160000,
          stock: 1000,
          image: 'kemeja_tkj.png',
          size: 'L',
          product_type_id: 1,
        },
        { 
          id: 32,
          name: 'Kemeja TKJ',
          price: 160000,
          stock: 1000,
          image: 'kemeja_tkj.png',
          size: 'XL',
          product_type_id: 1,
        },
    ]
      
    try {
        await Uniform.sync({ force: true })
        await Uniform.bulkCreate(UniformData)  
        console.log('Data Seragam berhasil disisipkan.')
    } catch (error) {
        console.error('Gagal menyisipkan data seragam:', error)
    }
}

export const getAllUniform = async () => {
    try {
        const rows = await Uniform.findAll({ group: 'name' })
        return rows
    } catch (error) {
        console.log('Gagal mengambil data seragam: ', error)
    }
}